// generated 2007/3/10 15:18:21 CET by tobias@donald.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /media/hdb5/workspace/JEliza/trunk/trunk/jeliza-glade/jeliza-glade.glade
// for gtk 2.8.17 and gtkmm 2.2.12
//
// Please modify the corresponding derived classes in ./src/MainWindow.hh and./src/MainWindow.cc

#ifndef _MAINWINDOW_GLADE_HH
#  define _MAINWINDOW_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>

class MainWindow_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
public:
        class Gtk::Window * MainWindow;
protected:
        
        MainWindow_glade();
        
        ~MainWindow_glade();
private:
        virtual void on_new_activate() = 0;
        virtual void on_open_activate() = 0;
        virtual void on_save_activate() = 0;
        virtual void on_close_activate() = 0;
        virtual void on_cut_activate() = 0;
        virtual void on_copy_activate() = 0;
        virtual void on_paste_activate() = 0;
        virtual void on_delete_activate() = 0;
        virtual void on_einstellungen_activate() = 0;
        virtual void on_info_activate() = 0;
        virtual bool on_entry_enter_notify_event(GdkEventCrossing *ev) = 0;
        virtual void on_Ask_clicked() = 0;
};
#endif
